###
POST http://localhost:9000/download HTTP/1.1
content-type: application/json

{
    "token": "YOUR-TOKEN"
}

###
GET http://localhost:9000/unzip

###
GET http://localhost:9000/split

###
GET http://localhost:9000/search?ip=8.8.8.8

###
GET http://localhost:9000/search?ip=2001:4860:4860:0:0:0:0:8888