version: "3"
services:
  iploc:
    build:
      context: .
      dockerfile: Dockerfile
    image: ivanglie/iploc:latest
    container_name: iploc
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TOKEN
      - SSL
      - HOST
      - DEBUG