services:
  api:
    build:
      context: .
    image: ivanglie/iploc-api:latest
    container_name: iploc-api
    restart: always
    environment:
      - TOKEN=${TOKEN}
      - DOMAIN=${DOMAIN}
    networks:
      - internal

  proxy:
    image: caddy:latest
    container_name: iploc-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - DOMAIN=${DOMAIN}
    depends_on:
      - api
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  caddy_data:
  caddy_config: