services:
  api:
    build:
      context: .
    image: ivanglie/iploc-api:latest
    container_name: iploc-api
    restart: always
    env_file:
      - .env.dev
    networks:
      - internal

  proxy:
    image: caddy:latest
    container_name: iploc-proxy
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile.dev:/etc/caddy/Caddyfile
    depends_on:
      - api
    networks:
      - internal

networks:
  internal:
    driver: bridge