FROM --platform=linux/amd64 golang:1.19-alpine

WORKDIR /usr/src/iploc/

COPY . .

RUN apk add --no-cache tzdata && go build -v -o /usr/local/bin/iploc ./cmd/app/

ENV TZ=Europe/Moscow

WORKDIR /tmp

CMD ["iploc"]