name: Docker Image CI/CD

on:
  push:
#     branches: [ "master" ]
  pull_request:
#     branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
        - uses: actions/checkout@v3
        
        - name: Setup key
          run: |
            set -eu
            mkdir "$HOME/.ssh"
            echo "${{ secrets.key }}" > "$HOME/.ssh/key"
            chmod 600 "$HOME/.ssh/key"

        # - name: Build image
        #   run: docker buildx build . --platform=linux/amd64 --file Dockerfile --tag iploc:$(date +%s)
          
        # - name: Save image
        #   run: |
        #       set -eu
        #       sudo docker save -o iploc.tar iploc

        
