name: Docker Image CI/CD

on:
  push:
#     branches: [ "master" ]
  pull_request:
#     branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Setup key
          run: |
                set -eu
                mkdir -p "$HOME/.ssh"
                echo "${{ secrets.key }}" > "$HOME/.ssh/key"
                chmod 600 "$HOME/.ssh/key"

        - uses: actions/checkout@v3
        - name: Build image
          run: docker buildx build . --platform=linux/amd64 --file Dockerfile --tag iploc:$(date +%s)
           
        - name: Save image
          run: |
                set -eu
                sudo mkdir -p "/usr/src/iploc"
                cd "/usr/src/iploc"
                sudo docker save -o iploc.tar iploc

        - name: Deploy image to remote host
          run: |
                echo ${{ env.login }}
                # ssh -i ${{ secrets.key }} ${{ secrets.login }} "sudo mkdir -p /usr/src/iploc"
                # rsync -e "ssh -i ${{ secrets.key }} -o StrictHostKeyChecking=no" --rsync-path "sudo rsync" --archive --compress --delete iploc.tar .env ${{ secrets.login }}:/usr/src/iploc
                
        # - name: Run container on remote host
        #   run: |
        #         ssh ${{ secrets.login }} 'bash -s' <<'ENDSSH'
        #           cd /usr/src/
        #           docker load -i iploc.tar
        #           docker run --env-file .env.prod -d -p 80:18001 iploc
        #         ENDSSH


           
     
    
