name: Docker Image CI/CD

on:
  push:
#     branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
        - uses: actions/checkout@v3
        
        - name: Setup SSH key
          run: |
            install -m 600 -D /dev/null ~/.ssh/id_rsa
            echo "${{ secrets.KEY }}" > ~/.ssh/id_rsa
            ssh-keyscan -H ${{ secrets.HOST }} > ~/.ssh/known_hosts

        - name: Prepare remote host
          run: |
            ssh -i ~/.ssh/id_rsa ${{ secrets.USER }}@${{ secrets.HOST }} "echo ${{ secrets.PASSWORD }} | sudo -S mkdir -p /usr/src/iploc"


        # - name: Build image
        #   run: docker buildx build . --platform=linux/amd64 --file Dockerfile --tag iploc:$(date +%s)
          
        # - name: Save image
        #   run: |
        #       set -eu
        #       sudo docker save -o iploc.tar iploc


        # - name: Copy files to remote host
        #   run: rsync -e "ssh -i $HOME/.ssh/id_rsa -o StrictHostKeyChecking=no" --archive --compress --delete iploc.tar .env ${{ secrets.USER }}@${{ secrets.HOST }}:/usr/src/iploc