name: Docker Image CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
        - uses: actions/checkout@v3
        
        - name: Setup SSH key
          run: |
            install -m 600 -D /dev/null ~/.ssh/id_rsa
            echo "${{ secrets.KEY }}" > ~/.ssh/id_rsa
            ssh-keyscan -H ${{ secrets.HOST }} > ~/.ssh/known_hosts

        - name: Create directory on remote server
          run: |
            ssh ${{ secrets.USER }}@${{ secrets.HOST }} "
            echo ${{ secrets.PASSWORD }} | sudo -S rm -r /usr/src/iploc
            echo ${{ secrets.PASSWORD }} | sudo -S mkdir -p /usr/src/iploc
            echo ${{ secrets.PASSWORD }} | sudo -S chmod 777 /usr/src/iploc"

        - name: Build image
          run: docker buildx build --platform=linux/amd64 --tag iploc:latest --file Dockerfile .
          
        - name: Save image
          run: |
            sudo docker save -o iploc.tar iploc:latest
            sudo chmod 777 iploc.tar

        - name: Copy files to remote host
          run: rsync -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" --archive --compress --delete iploc.tar .env ${{ secrets.USER }}@${{ secrets.HOST }}:/usr/src/iploc

        - name: Load and run docker container on remote host
          run: |
            ssh ${{ secrets.USER }}@${{ secrets.HOST }} "
            echo ${{ secrets.PASSWORD }} | sudo -S docker load -i /usr/src/iploc/iploc.tar
            echo ${{ secrets.PASSWORD }} | sudo -S docker run --env-file /usr/src/iploc/.env -d -p 18001:18001 iploc:latest"