name: Docker Image CI/CD

on:
  push:
#     branches: [ "master" ]
  pull_request:
#     branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Setup key
          run: |
                set -eu
                mkdir -p "$HOME/.ssh"
                echo "${{ secrets.key }}" > "$HOME/.ssh/key"
                chmod 600 "$HOME/.ssh/key"

        - uses: actions/checkout@v3
        - name: Build the Docker image
          run: docker build . --file Dockerfile --tag iploc:$(date +%s)
           
        - name: Save image
          run: |
                set -eu
                cd $Home/usr/src/
                mkdir -p "iploc"
                docker save -o $Home/usr/src/iploc/iploc.tar iploc


           
     
    
